### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by OllieClarke** [edxhayter/GitHub-Action-Python-Demo#2]
Should be "What are Github actions" in slide 2

**Comment by OllieClarke** [comment]
Based on illuminating conversation with Ed, I'll close this issue ceding defeat

**Comment by edxhayter** [comment]
"GitHub Actions **is** a continuous integration and continuous delivery (CI/CD) platform" - based on the [link](https://docs.github.com/actions/learn-github-actions/understanding-github-actions)
